### ISSUE TITLE
Double tap on 'Must see'or 'Movie' causes app to crash 

### ISSUE THREAD

**Issue by Olamatto** [spacepandas/cineaste-android#28]
#### Expected behavior
App is expected to work perfectly well, in any state or condition, not leading to crash. 

#### Actual Behavior 
While trying to add a movie to watchlist or history, double clicking on Must see or Movies makes the app crash.

#### How to reproduce
- Download and install the application [here](https://play.google.com/store/apps/details?id=de.cineaste.android&pcampaignid=MKT-Other-global-all-co-prtnr-py-PartBadge-Mar2515-1)
- Switch on your data connection 
- Launch the application 
- In the watchlist section, click on the add button 
- After loading, from the add section, double click on Must see or Movies 

Then app crashes 

<hr>

Application version: v2.4.0
Operating system: Android v7.0

#### Recording Of The Bug
https://youtu.be/5T13h6OvMSQ

**Comment by marcelgross90** [comment]
Will be fixed with next version
