### ISSUE TITLE
APK file broken

### ISSUE THREAD

**Issue by IzzySoft** [spacepandas/cineaste-android#38]
The APK file in `app/release/app-release.apk` is broken (0 byte). Maybe you remove it there – and instead attach it to the corresponding release (in `releases/`)?

**Comment by marcelgross90** [comment]
Sorry the APK shouldn't be in the repository anyway. So I removed it.

**Comment by IzzySoft** [comment]
@marcelgross90 I agree with you it shouldn't be *there* – but it might be a good idea having it attached to [`releases/`](https://github.com/spacepandas/cineaste-android/releases) :smiley:

**Comment by IzzySoft** [comment]
Any chance @marcelgross90? Some folks (like me) don't use Play Store, or can't even. I gladly provide it via [my F-Droid repo](https://apt.izzysoft.de/fdroid) (the official one wouldn't accept it because of GCM), but I'd need the APK (preferably via `releases/`).

**Comment by marcelgross90** [comment]
I will attach the APK files soon

**Comment by IzzySoft** [comment]
Great! Thanks a lot!

**Comment by marcelgross90** [comment]
For now I added the latest version. Which I released today.
Should be enough?

**Comment by IzzySoft** [comment]
Yes indeed, thanks! If you could continue that for future releases, my updater would grab them within 24h of your doing so.

I've initiated the record, and Cineaste should [show up here](https://apt.izzysoft.de/fdroid/index/apk/de.cineaste.android) within 24h (well, 23h actually – just missed the last sync).

Big thanks again! Let me know if you like something e.g. in the description changed (I've basically taken that and the screenshots from the Play Store listing).
